baseURL = 'https://lockyc.com/'
languageCode = 'en-au'
title = 'Lockyc'
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[params]
	author = "Lachlan Collins"
	description = "Ranting into the void"
	avatar = "https://avatars.githubusercontent.com/u/1438799?v=4"
	[[params.social]]
    icon = "github"
   	name = "Github"
   	url = "https://github.com/Lockyc"
  [[params.social]]
   	icon = "twitter"
   	name = "Twitter"
   	url = "https://twitter.com/Delusional"
